import type { Theme } from '../context/ThemeContext';

const darkAppearance = {
  variables: {
    colorPrimary: '#FFFFFF',
    colorText: '#FFFFFF',
    colorTextSecondary: '#B5B5B5',
    colorBackground: '#0B0B0B',
    colorInputBackground: '#0D0D0D',
    colorInputText: '#FFFFFF',
    colorNeutral: '#2A2A2A',
    colorDanger: '#FFFFFF',
    borderRadius: '16px',
    fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
    fontFamilyButtons: 'Inter, system-ui, -apple-system, sans-serif',
    fontSize: '14px',
    fontWeight: { normal: 400, medium: 500, bold: 600 },
  },
  elements: {
    rootBox: 'w-full',
    card: '!bg-[var(--bg-card)] !border-[var(--border-default)] rounded-2xl shadow-2xl shadow-[var(--black-alpha-50)]',
    headerTitle: '!text-[var(--text-primary)] text-xl font-display font-bold tracking-tight',
    headerSubtitle: '!text-[var(--text-muted)] text-sm',
    header: 'pb-0 mb-1',
    formFieldLabel: '!text-[var(--text-secondary)] text-sm font-medium mb-1.5',
    formFieldInput: '!bg-[var(--bg-input)] !border-[var(--border-default)] rounded-xl !text-[var(--text-primary)] placeholder:!text-[var(--text-muted)] focus:!border-[var(--text-primary)] focus:ring-0 focus:!bg-[var(--bg-input)] px-4 py-2.5 text-sm transition-colors',
    formButtonPrimary: '!bg-[var(--btn-bg)] !text-[var(--btn-text)] rounded-xl hover:!bg-[var(--btn-hover)] text-sm font-medium py-2.5 shadow-lg shadow-[var(--white-alpha-10)] transition-all',
    footerActionLink: '!text-[var(--text-muted)] hover:!text-[var(--text-primary)] text-sm transition-colors',
    footerActionText: '!text-[var(--text-muted)] text-sm',
    dividerLine: '!bg-[var(--border-default)]',
    dividerText: '!text-[var(--text-muted)] text-xs',
    socialButtonsIconButton: '!bg-[var(--btn-bg)] !border-[var(--border-default)] rounded-xl hover:!bg-[var(--btn-hover)] transition-all',
    socialButtonsBlockButton: '!bg-[var(--btn-bg)] !border-[var(--border-default)] rounded-xl !text-[var(--btn-text)] hover:!bg-[var(--btn-hover)] text-sm font-medium transition-all',
    formFieldAction: '!text-[var(--text-muted)] hover:!text-[var(--text-primary)] text-xs transition-colors',
    formHeaderTitle: '!text-[var(--text-primary)] text-lg font-display font-semibold',
    formHeaderSubtitle: '!text-[var(--text-muted)] text-xs',
    alertText: '!text-[var(--text-primary)] !bg-[var(--bg-input)] !border-[var(--border-default)] rounded-xl text-sm',
    alertTextDanger: '!text-[var(--text-primary)]',
    formResendCodeLink: '!text-[var(--text-secondary)] hover:!text-[var(--text-primary)] transition-colors',
    formFieldInputShowPasswordButton: '!text-[var(--text-muted)] hover:!text-[var(--text-primary)] transition-colors',
    formFieldSuccessText: 'text-[var(--white-alpha-20)] text-xs',
    formFieldErrorText: 'text-[var(--white-alpha-20)] text-xs',
    identityPreviewText: '!text-[var(--text-secondary)]',
    identityPreview: '!bg-[var(--bg-input)] !border-[var(--border-soft)] rounded-xl p-4',
    userButtonAvatarBox: 'w-8 h-8 rounded-full !border-2 !border-[var(--border-default)] !bg-[var(--bg-elevated)]',
    userButtonTrigger: 'hover:opacity-80 transition-opacity',
    userButtonPopoverCard: '!bg-[var(--bg-secondary)] !border-[var(--border-default)] rounded-[18px] shadow-2xl shadow-[var(--black-alpha-60)] p-1.5',
    userButtonPopoverActionButton: 'flex items-center gap-3 w-full px-3 py-2.5 rounded-xl text-sm hover:!bg-[var(--hover-bg)] transition-colors',
    userButtonPopoverActionButtonText: '!text-[var(--text-primary)] text-sm font-medium',
    userButtonPopoverFooter: '!border-t !border-[var(--border-default)] mt-1 pt-1 px-1',
    userButtonOuterIdentifier: '!text-[var(--text-muted)] text-xs',
    userButtonMenuText: '!text-[var(--text-primary)] text-sm',
    userButtonMenuIcon: '!text-[var(--text-muted)]',
    modalContent: '!bg-[var(--bg-card)] !border-[var(--border-default)] rounded-2xl shadow-2xl shadow-[var(--black-alpha-60)]',
    modalCloseButton: '!text-[var(--text-muted)] hover:!text-[var(--text-primary)] transition-colors w-8 h-8 rounded-lg hover:!bg-[var(--hover-bg)] flex items-center justify-center',
    navbar: '!bg-[var(--bg-main)] !border-r !border-[var(--border-default)] px-3 py-4',
    navbarButton: '!text-[var(--text-muted)] hover:!text-[var(--text-primary)] hover:!bg-[var(--hover-bg)] rounded-xl px-3 py-2.5 text-sm font-medium transition-colors w-full text-left',
    navbarButtonIcon: '!text-[var(--text-muted)]',
    profileSection: '!border-b !border-[var(--border-soft)] pb-6 mb-6',
    profileSectionTitle: '!text-[var(--text-primary)] text-sm font-semibold',
    profileSectionTitleText: '!text-[var(--text-primary)]',
    profileSectionContent: '!text-[var(--text-secondary)]',
    menuButton: '!text-[var(--text-muted)] hover:!text-[var(--text-primary)] transition-colors',
    menuList: '!bg-[var(--bg-card)] !border-[var(--border-default)] rounded-2xl shadow-2xl shadow-[var(--black-alpha-50)] p-1',
    menuItem: '!text-[var(--text-secondary)] hover:!text-[var(--text-primary)] hover:!bg-[var(--btn-dark-hover)] rounded-xl px-3 py-2 text-sm transition-colors',
    badge: '!bg-[var(--bg-input)] !border-[var(--border-default)] !text-[var(--text-primary)] rounded-lg px-2 py-0.5 text-xs',
    avatarBox: '!border-2 !border-[var(--border-default)] rounded-full',
    avatarImage: 'rounded-full',
    userPreviewMainIdentifier: '!text-[var(--text-primary)] text-base font-semibold',
    userPreviewSecondaryIdentifier: '!text-[var(--text-muted)] text-sm',
    activeDeviceIcon: '!text-[var(--text-primary)]',
    accordionTrigger: '!text-[var(--text-primary)] hover:!text-[var(--text-secondary)] text-sm font-medium transition-colors',
    accordionContent: '!text-[var(--text-secondary)] text-sm',
    dangerButton: 'bg-transparent !border-[var(--border-default)] !text-[var(--text-primary)] hover:!bg-[var(--btn-dark-hover)] rounded-xl text-sm transition-colors',
    phoneNumberPreview: '!text-[var(--text-secondary)]',
    backButton: '!text-[var(--text-muted)] hover:!text-[var(--text-primary)] transition-colors',
  },
};

const lightAppearance = {
  variables: {
    colorPrimary: '#000000',
    colorText: '#1D1D1F',
    colorTextSecondary: '#6E6E73',
    colorBackground: '#FFFFFF',
    colorInputBackground: '#F8F8FA',
    colorInputText: '#1D1D1F',
    colorNeutral: '#E5E5E7',
    colorDanger: '#DC2626',
    borderRadius: '16px',
    fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
    fontFamilyButtons: 'Inter, system-ui, -apple-system, sans-serif',
    fontSize: '14px',
    fontWeight: { normal: 400, medium: 500, bold: 600 },
  },
  elements: {
    rootBox: 'w-full',
    card: '!bg-white !border-[var(--border-default)] rounded-2xl shadow-lg shadow-[var(--black-alpha-50)]',
    headerTitle: '!text-[var(--text-primary)] text-xl font-display font-bold tracking-tight',
    headerSubtitle: '!text-[var(--text-muted)] text-sm',
    header: 'pb-0 mb-1',
    formFieldLabel: '!text-[var(--text-secondary)] text-sm font-medium mb-1.5',
    formFieldInput: '!bg-[var(--bg-input)] !border-[var(--border-default)] rounded-xl !text-[var(--text-primary)] placeholder:!text-[var(--text-muted)] focus:!border-[var(--text-primary)] focus:ring-0 focus:!bg-[var(--bg-input)] px-4 py-2.5 text-sm transition-colors',
    formButtonPrimary: '!bg-[var(--btn-bg)] !text-[var(--btn-text)] rounded-xl hover:!bg-[var(--btn-hover)] text-sm font-medium py-2.5 shadow-lg shadow-[var(--white-alpha-10)] transition-all',
    footerActionLink: '!text-[var(--text-muted)] hover:!text-[var(--text-primary)] text-sm transition-colors',
    footerActionText: '!text-[var(--text-muted)] text-sm',
    dividerLine: '!bg-[var(--border-default)]',
    dividerText: '!text-[var(--text-muted)] text-xs',
    socialButtonsIconButton: '!bg-[var(--btn-bg)] !border-[var(--border-default)] rounded-xl hover:!bg-[var(--btn-hover)] transition-all',
    socialButtonsBlockButton: '!bg-[var(--btn-bg)] !border-[var(--border-default)] rounded-xl !text-[var(--btn-text)] hover:!bg-[var(--btn-hover)] text-sm font-medium transition-all',
    formFieldAction: '!text-[var(--text-muted)] hover:!text-[var(--text-primary)] text-xs transition-colors',
    formHeaderTitle: '!text-[var(--text-primary)] text-lg font-display font-semibold',
    formHeaderSubtitle: '!text-[var(--text-muted)] text-xs',
    alertText: '!text-[var(--text-primary)] !bg-[var(--bg-input)] !border-[var(--border-default)] rounded-xl text-sm',
    alertTextDanger: '!text-[var(--text-primary)]',
    formResendCodeLink: '!text-[var(--text-secondary)] hover:!text-[var(--text-primary)] transition-colors',
    formFieldInputShowPasswordButton: '!text-[var(--text-muted)] hover:!text-[var(--text-primary)] transition-colors',
    formFieldSuccessText: 'text-[var(--white-alpha-20)] text-xs',
    formFieldErrorText: 'text-[var(--white-alpha-20)] text-xs',
    identityPreviewText: '!text-[var(--text-secondary)]',
    identityPreview: '!bg-[var(--bg-input)] !border-[var(--border-soft)] rounded-xl p-4',
    userButtonAvatarBox: 'w-8 h-8 rounded-full !border-2 !border-[var(--border-default)] !bg-[var(--bg-elevated)]',
    userButtonTrigger: 'hover:opacity-80 transition-opacity',
    userButtonPopoverCard: '!bg-white !border-[var(--border-default)] rounded-[18px] shadow-2xl shadow-[var(--black-alpha-60)] p-1.5',
    userButtonPopoverActionButton: 'flex items-center gap-3 w-full px-3 py-2.5 rounded-xl text-sm hover:!bg-[var(--hover-bg)] transition-colors',
    userButtonPopoverActionButtonText: '!text-[var(--text-primary)] text-sm font-medium',
    userButtonPopoverFooter: '!border-t !border-[var(--border-default)] mt-1 pt-1 px-1',
    userButtonOuterIdentifier: '!text-[var(--text-muted)] text-xs',
    userButtonMenuText: '!text-[var(--text-primary)] text-sm',
    userButtonMenuIcon: '!text-[var(--text-muted)]',
    modalContent: '!bg-white !border-[var(--border-default)] rounded-2xl shadow-2xl shadow-[var(--black-alpha-60)]',
    modalCloseButton: '!text-[var(--text-muted)] hover:!text-[var(--text-primary)] transition-colors w-8 h-8 rounded-lg hover:!bg-[var(--hover-bg)] flex items-center justify-center',
    navbar: '!bg-white !border-r !border-[var(--border-default)] px-3 py-4',
    navbarButton: '!text-[var(--text-muted)] hover:!text-[var(--text-primary)] hover:!bg-[var(--hover-bg)] rounded-xl px-3 py-2.5 text-sm font-medium transition-colors w-full text-left',
    navbarButtonIcon: '!text-[var(--text-muted)]',
    profileSection: '!border-b !border-[var(--border-soft)] pb-6 mb-6',
    profileSectionTitle: '!text-[var(--text-primary)] text-sm font-semibold',
    profileSectionTitleText: '!text-[var(--text-primary)]',
    profileSectionContent: '!text-[var(--text-secondary)]',
    menuButton: '!text-[var(--text-muted)] hover:!text-[var(--text-primary)] transition-colors',
    menuList: '!bg-white !border-[var(--border-default)] rounded-2xl shadow-2xl shadow-[var(--black-alpha-50)] p-1',
    menuItem: '!text-[var(--text-secondary)] hover:!text-[var(--text-primary)] hover:!bg-[var(--btn-dark-hover)] rounded-xl px-3 py-2 text-sm transition-colors',
    badge: '!bg-[var(--bg-input)] !border-[var(--border-default)] !text-[var(--text-primary)] rounded-lg px-2 py-0.5 text-xs',
    avatarBox: '!border-2 !border-[var(--border-default)] rounded-full',
    avatarImage: 'rounded-full',
    userPreviewMainIdentifier: '!text-[var(--text-primary)] text-base font-semibold',
    userPreviewSecondaryIdentifier: '!text-[var(--text-muted)] text-sm',
    activeDeviceIcon: '!text-[var(--text-primary)]',
    accordionTrigger: '!text-[var(--text-primary)] hover:!text-[var(--text-secondary)] text-sm font-medium transition-colors',
    accordionContent: '!text-[var(--text-secondary)] text-sm',
    dangerButton: 'bg-transparent !border-[var(--border-default)] !text-[var(--text-primary)] hover:!bg-[var(--btn-dark-hover)] rounded-xl text-sm transition-colors',
    phoneNumberPreview: '!text-[var(--text-secondary)]',
    backButton: '!text-[var(--text-muted)] hover:!text-[var(--text-primary)] transition-colors',
  },
};

export function getClerkAppearance(theme: Theme) {
  if (theme === 'light') return lightAppearance;
  return darkAppearance;
}
